### ISSUE TITLE
Missing curency Translation

### ISSUE THREAD

**Issue by Zukko04** [realwakils/buffcurrency#1]
![Screenshot 2021-03-31 170907](https://user-images.githubusercontent.com/81699806/113167266-d8a3a700-9243-11eb-845e-fbd520f8ee15.png)
![image](https://user-images.githubusercontent.com/81699806/113167389-f7a23900-9243-11eb-9b60-2e1235d3e0f1.png)

Its under the market tab.

**Comment by realwakils** [comment]
there are multiple issues with this, which is why i've decided to close this issue for now.

(easily) we can only modify and manipulate what the user sees. the server still thinks the price we want is in chinese yuan. would be too difficult and unnecessary
