### ISSUE TITLE
[BUG] Extension only changing currency to previously set one

### ISSUE THREAD

**Issue by AmirJaber97** [realwakils/buffcurrency#10]
In order to change the currency, you'd have to change the currency twice. The previous selected currency would be the one being used.

Browser: Opera GX - using the chrome extension

![image](https://user-images.githubusercontent.com/39519247/120197279-7823ec80-c229-11eb-9718-8bd6532fbeb0.png)

**Comment by realwakils** [comment]
I've noticed this behaviour on my dad's Macbook aswell. Seems like there's
some compatibility issues. I'm looking into it, thank you for the bug
report.

**Comment by realwakils** [comment]
Hello @AmirJaber97 I tried to replicate your issue, by downloading Opera GX to my Windows machine. It does seem to working fine for me though. Could you tell me which OS you are on?

I downloaded the "Install Google Extensions" thingy and then installed Buff Currency. Did you do the same? My UI seems to be a bit different
![image](https://user-images.githubusercontent.com/19620638/120505943-c241d500-c3c5-11eb-806e-56dcaf2ce493.png)

**Comment by linnnus** [comment]
This was an issue with the old design and has been fixed with the rewrite (https://github.com/realwakils/buffcurrency/commit/30798e2740ec2b023c3fb18775421b8c9606143f) so I guess we can close this now.
